//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapAPIConnector.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.edi.exite.org", ConfigurationName="ServiceReference.ExiteWs")]
    public interface ExiteWs {
        
        // CODEGEN: Контракт генерации сообщений с операцией getDocuments не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapAPIConnector.ServiceReference.getDocumentsResponse1 getDocuments(SoapAPIConnector.ServiceReference.getDocumentsRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией uploadDoc не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapAPIConnector.ServiceReference.uploadDocResponse1 uploadDoc(SoapAPIConnector.ServiceReference.uploadDocRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией archiveDocuments не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapAPIConnector.ServiceReference.archiveDocumentsResponse1 archiveDocuments(SoapAPIConnector.ServiceReference.archiveDocumentsRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getList не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapAPIConnector.ServiceReference.getListResponse1 getList(SoapAPIConnector.ServiceReference.getListRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getDoc не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapAPIConnector.ServiceReference.getDocResponse1 getDoc(SoapAPIConnector.ServiceReference.getDocRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией archiveDoc не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapAPIConnector.ServiceReference.archiveDocResponse1 archiveDoc(SoapAPIConnector.ServiceReference.archiveDocRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией sendDoc не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapAPIConnector.ServiceReference.sendDocResponse1 sendDoc(SoapAPIConnector.ServiceReference.sendDocRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class getDocumentsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string[] fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.edi.exite.org")]
    public partial class ediLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("pass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ediFileList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ediFile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.edi.exite.org")]
    public partial class ediResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.edi.exite.org")]
    public partial class ediFileList : ediResponse {
        
        private string[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("list");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.edi.exite.org")]
    public partial class ediFile : ediResponse {
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class getDocumentsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediFile resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediFile result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.getDocumentsRequest getDocumentsRequest;
        
        public getDocumentsRequest1() {
        }
        
        public getDocumentsRequest1(SoapAPIConnector.ServiceReference.getDocumentsRequest getDocumentsRequest) {
            this.getDocumentsRequest = getDocumentsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.getDocumentsResponse getDocumentsResponse;
        
        public getDocumentsResponse1() {
        }
        
        public getDocumentsResponse1(SoapAPIConnector.ServiceReference.getDocumentsResponse getDocumentsResponse) {
            this.getDocumentsResponse = getDocumentsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class uploadDocRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string fileNameField;
        
        private byte[] contentField;
        
        private string remoteFolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=2)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string remoteFolder {
            get {
                return this.remoteFolderField;
            }
            set {
                this.remoteFolderField = value;
                this.RaisePropertyChanged("remoteFolder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class uploadDocResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadDocRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.uploadDocRequest uploadDocRequest;
        
        public uploadDocRequest1() {
        }
        
        public uploadDocRequest1(SoapAPIConnector.ServiceReference.uploadDocRequest uploadDocRequest) {
            this.uploadDocRequest = uploadDocRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadDocResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.uploadDocResponse uploadDocResponse;
        
        public uploadDocResponse1() {
        }
        
        public uploadDocResponse1(SoapAPIConnector.ServiceReference.uploadDocResponse uploadDocResponse) {
            this.uploadDocResponse = uploadDocResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class archiveDocumentsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string[] fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class archiveDocumentsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archiveDocumentsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.archiveDocumentsRequest archiveDocumentsRequest;
        
        public archiveDocumentsRequest1() {
        }
        
        public archiveDocumentsRequest1(SoapAPIConnector.ServiceReference.archiveDocumentsRequest archiveDocumentsRequest) {
            this.archiveDocumentsRequest = archiveDocumentsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archiveDocumentsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.archiveDocumentsResponse archiveDocumentsResponse;
        
        public archiveDocumentsResponse1() {
        }
        
        public archiveDocumentsResponse1(SoapAPIConnector.ServiceReference.archiveDocumentsResponse archiveDocumentsResponse) {
            this.archiveDocumentsResponse = archiveDocumentsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class getListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class getListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediFileList resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediFileList result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.getListRequest getListRequest;
        
        public getListRequest1() {
        }
        
        public getListRequest1(SoapAPIConnector.ServiceReference.getListRequest getListRequest) {
            this.getListRequest = getListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.getListResponse getListResponse;
        
        public getListResponse1() {
        }
        
        public getListResponse1(SoapAPIConnector.ServiceReference.getListResponse getListResponse) {
            this.getListResponse = getListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class getDocRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class getDocResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediFile resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediFile result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.getDocRequest getDocRequest;
        
        public getDocRequest1() {
        }
        
        public getDocRequest1(SoapAPIConnector.ServiceReference.getDocRequest getDocRequest) {
            this.getDocRequest = getDocRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.getDocResponse getDocResponse;
        
        public getDocResponse1() {
        }
        
        public getDocResponse1(SoapAPIConnector.ServiceReference.getDocResponse getDocResponse) {
            this.getDocResponse = getDocResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class archiveDocRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class archiveDocResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archiveDocRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.archiveDocRequest archiveDocRequest;
        
        public archiveDocRequest1() {
        }
        
        public archiveDocRequest1(SoapAPIConnector.ServiceReference.archiveDocRequest archiveDocRequest) {
            this.archiveDocRequest = archiveDocRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archiveDocResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.archiveDocResponse archiveDocResponse;
        
        public archiveDocResponse1() {
        }
        
        public archiveDocResponse1(SoapAPIConnector.ServiceReference.archiveDocResponse archiveDocResponse) {
            this.archiveDocResponse = archiveDocResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class sendDocRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string fileNameField;
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=2)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.exite.org")]
    public partial class sendDocResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendDocRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.sendDocRequest sendDocRequest;
        
        public sendDocRequest1() {
        }
        
        public sendDocRequest1(SoapAPIConnector.ServiceReference.sendDocRequest sendDocRequest) {
            this.sendDocRequest = sendDocRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendDocResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.exite.org", Order=0)]
        public SoapAPIConnector.ServiceReference.sendDocResponse sendDocResponse;
        
        public sendDocResponse1() {
        }
        
        public sendDocResponse1(SoapAPIConnector.ServiceReference.sendDocResponse sendDocResponse) {
            this.sendDocResponse = sendDocResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExiteWsChannel : SoapAPIConnector.ServiceReference.ExiteWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExiteWsClient : System.ServiceModel.ClientBase<SoapAPIConnector.ServiceReference.ExiteWs>, SoapAPIConnector.ServiceReference.ExiteWs {
        
        public ExiteWsClient() {
        }
        
        public ExiteWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExiteWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExiteWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExiteWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapAPIConnector.ServiceReference.getDocumentsResponse1 SoapAPIConnector.ServiceReference.ExiteWs.getDocuments(SoapAPIConnector.ServiceReference.getDocumentsRequest1 request) {
            return base.Channel.getDocuments(request);
        }
        
        public SoapAPIConnector.ServiceReference.getDocumentsResponse getDocuments(SoapAPIConnector.ServiceReference.getDocumentsRequest getDocumentsRequest) {
            SoapAPIConnector.ServiceReference.getDocumentsRequest1 inValue = new SoapAPIConnector.ServiceReference.getDocumentsRequest1();
            inValue.getDocumentsRequest = getDocumentsRequest;
            SoapAPIConnector.ServiceReference.getDocumentsResponse1 retVal = ((SoapAPIConnector.ServiceReference.ExiteWs)(this)).getDocuments(inValue);
            return retVal.getDocumentsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapAPIConnector.ServiceReference.uploadDocResponse1 SoapAPIConnector.ServiceReference.ExiteWs.uploadDoc(SoapAPIConnector.ServiceReference.uploadDocRequest1 request) {
            return base.Channel.uploadDoc(request);
        }
        
        public SoapAPIConnector.ServiceReference.uploadDocResponse uploadDoc(SoapAPIConnector.ServiceReference.uploadDocRequest uploadDocRequest) {
            SoapAPIConnector.ServiceReference.uploadDocRequest1 inValue = new SoapAPIConnector.ServiceReference.uploadDocRequest1();
            inValue.uploadDocRequest = uploadDocRequest;
            SoapAPIConnector.ServiceReference.uploadDocResponse1 retVal = ((SoapAPIConnector.ServiceReference.ExiteWs)(this)).uploadDoc(inValue);
            return retVal.uploadDocResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapAPIConnector.ServiceReference.archiveDocumentsResponse1 SoapAPIConnector.ServiceReference.ExiteWs.archiveDocuments(SoapAPIConnector.ServiceReference.archiveDocumentsRequest1 request) {
            return base.Channel.archiveDocuments(request);
        }
        
        public SoapAPIConnector.ServiceReference.archiveDocumentsResponse archiveDocuments(SoapAPIConnector.ServiceReference.archiveDocumentsRequest archiveDocumentsRequest) {
            SoapAPIConnector.ServiceReference.archiveDocumentsRequest1 inValue = new SoapAPIConnector.ServiceReference.archiveDocumentsRequest1();
            inValue.archiveDocumentsRequest = archiveDocumentsRequest;
            SoapAPIConnector.ServiceReference.archiveDocumentsResponse1 retVal = ((SoapAPIConnector.ServiceReference.ExiteWs)(this)).archiveDocuments(inValue);
            return retVal.archiveDocumentsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapAPIConnector.ServiceReference.getListResponse1 SoapAPIConnector.ServiceReference.ExiteWs.getList(SoapAPIConnector.ServiceReference.getListRequest1 request) {
            return base.Channel.getList(request);
        }
        
        public SoapAPIConnector.ServiceReference.getListResponse getList(SoapAPIConnector.ServiceReference.getListRequest getListRequest) {
            SoapAPIConnector.ServiceReference.getListRequest1 inValue = new SoapAPIConnector.ServiceReference.getListRequest1();
            inValue.getListRequest = getListRequest;
            SoapAPIConnector.ServiceReference.getListResponse1 retVal = ((SoapAPIConnector.ServiceReference.ExiteWs)(this)).getList(inValue);
            return retVal.getListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapAPIConnector.ServiceReference.getDocResponse1 SoapAPIConnector.ServiceReference.ExiteWs.getDoc(SoapAPIConnector.ServiceReference.getDocRequest1 request) {
            return base.Channel.getDoc(request);
        }
        
        public SoapAPIConnector.ServiceReference.getDocResponse getDoc(SoapAPIConnector.ServiceReference.getDocRequest getDocRequest) {
            SoapAPIConnector.ServiceReference.getDocRequest1 inValue = new SoapAPIConnector.ServiceReference.getDocRequest1();
            inValue.getDocRequest = getDocRequest;
            SoapAPIConnector.ServiceReference.getDocResponse1 retVal = ((SoapAPIConnector.ServiceReference.ExiteWs)(this)).getDoc(inValue);
            return retVal.getDocResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapAPIConnector.ServiceReference.archiveDocResponse1 SoapAPIConnector.ServiceReference.ExiteWs.archiveDoc(SoapAPIConnector.ServiceReference.archiveDocRequest1 request) {
            return base.Channel.archiveDoc(request);
        }
        
        public SoapAPIConnector.ServiceReference.archiveDocResponse archiveDoc(SoapAPIConnector.ServiceReference.archiveDocRequest archiveDocRequest) {
            SoapAPIConnector.ServiceReference.archiveDocRequest1 inValue = new SoapAPIConnector.ServiceReference.archiveDocRequest1();
            inValue.archiveDocRequest = archiveDocRequest;
            SoapAPIConnector.ServiceReference.archiveDocResponse1 retVal = ((SoapAPIConnector.ServiceReference.ExiteWs)(this)).archiveDoc(inValue);
            return retVal.archiveDocResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapAPIConnector.ServiceReference.sendDocResponse1 SoapAPIConnector.ServiceReference.ExiteWs.sendDoc(SoapAPIConnector.ServiceReference.sendDocRequest1 request) {
            return base.Channel.sendDoc(request);
        }
        
        public SoapAPIConnector.ServiceReference.sendDocResponse sendDoc(SoapAPIConnector.ServiceReference.sendDocRequest sendDocRequest) {
            SoapAPIConnector.ServiceReference.sendDocRequest1 inValue = new SoapAPIConnector.ServiceReference.sendDocRequest1();
            inValue.sendDocRequest = sendDocRequest;
            SoapAPIConnector.ServiceReference.sendDocResponse1 retVal = ((SoapAPIConnector.ServiceReference.ExiteWs)(this)).sendDoc(inValue);
            return retVal.sendDocResponse;
        }
    }
}
